global using Enews.Persistence;
global using Enews.Application.Application;
global using Enews.Application.Mapping;
global using Enews.Application.Interfaces;
global using System.Reflection;
global using Microsoft.AspNetCore.Mvc;
global using AutoMapper;
global using Enews.Application.Models;
global using Enews.WebApi.Models.News;
